meta_product_name: "The Mob Club"
meta_title: "The Mob Club - A way to organize crimes free of hassle!"
meta_description: "A way to organize crimes free of hassle!"
meta_image: "og-image.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards