puts "Destorying Skillsets!"
Skillset.destroy_all
puts "Destroying users..."
User.destroy_all

puts "Destroying Crimes"
Crime.destroy_all

user_1 = User.create!(username: "ashelby", email: "gipsyforlife@exemple.com", password: "123456", , description: "By the order of Peaky Blinders! I'm Thomas Shelby. Widower, father of two, World wild known entrepenur, based on Birmingham, London and Boston USA. Owner of a lot of legal and illegal enterprises, such as; horse beting, steal companys, gin and liquor distilarys, pubs and nightclubs. Also did some governance works. Elected parliament at the house of common as member of socialist party. The Leader of the Peaky 'FUCKIN' Blinders.")
user_2 = User.create!(username: "gfather1", email: "bossvito@exemple.com", password: "123456", , description: "Vito Corleone: Best known as the Godfather. The biggest mob leader of the Corleone family. Original from Sicily. Protection and money loan are the talent of the family. But if don't kiss the ring you might wake up with a horse head on your bed! Capice?")
user_3 = User.create!(username: "alfielondon", email: "heyjude@exemple.com", password: "123456", , description: "")
user_4 = User.create!(username: "say_hello_to_my_little_friend", email: "", password: "123456", , description: "")
user_5 = User.create!(username: "tucoloco", email: "cartel_tuco@exemple.com", password: "123456", , description: "")
user_6 = User.create!(username: "mustacheshelby", email: "arthur@exemple.com", password: "123456", , description: "Arthur Shelby: I shoot first, ask later. Not here to waste time. Some say I’m more brawn than brains, but I think of myself as being a healthy type of impulsive. I’m very good with all types of guns. Fists speak louder than words, and I live by it. Mess with my family, and you will have your days on this earth counted.")
user_7 = User.create!(username: "pol", email: "gipsyqueen@exemple.com", password: "123456", , description: "Polly Gray: I’m known as being the matriarch on the family - I make good decisions, and give good advise, regardless if people agree with me or not, but generally, I am very diplomatic and good at convincing people. My biggest asset is my wisdom, but if you anger me like some policemen did in the past, I might pull out my Colt 45.")
user_8 = User.create!(username: "thebridge", email: "fuckbill@exemple.com", password: "123456", , description: "Beatrix Kiddo: I’m one of the best killers of the globe, and probably the best with all types of knives, but for good rewarding killings, I will use my Hattori Hanzo sword. And oh boy, it slices limbs like butter. I was killed and reborn, like a phoenix risen from the ashes. Hire me for some good old bloodshed, like in the good old days.")
user_9 = User.create!(username: "casinoboy", email: "vivalasvegas@exemple.com", password: "123456", , description: "Danny Ocean: I just got out of prison - after 4 years, I am ready to take over the world. Experienced in working in teams, I am one of the best thieves around - diplomatic, sneaky, and most important - charming. Don’t bother contacting me for feeble work - I’m here for generous rewards only.")
user_10 = User.create!(username: "bosswife", email: "bosswife@exemple.com", password: "123456", , description: "Mia Wallace: I’m married to a big gangster known in my hometown. Aspiring to become an actress, but I get bored sometimes, so I’m looking to put my skills to good use. I like milkshakes with burgers, and I value the silence between two people.")

s1 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_1)
s2 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_2)
s3 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_3)
s4 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_4)
s5 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_5)
s6 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_6)
s7 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_7)
s1 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_8)
s9 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_9)
s10 = Skillset.create!(close_combat: rand(1..10), long_range_weapons: rand(1..10), mid_range_weapons: rand(1..10), explosives: rand(1..10), infiltration: rand(1..10), lockpicking: rand(1..10), seduction: rand(1..10), skillset_id: user_10)

c1 = Crime.create!(title: "Bank robery at Lisbon", description: "Bank robery already plan. needed 3 man or woman with minimum 5 sucessful bank robs. bring your own weapon is a plus. Very good reward. we provide the costumes if necessary. We are not responsible in casualties or arrest. Apply now.", date: Time.new(2020, 12, 15, 17, 20, 0, "+01:00") , location: "Lisbon", reward: rand(500..30000))
c2 = Crime.create!(title: "Milion Euros Heist", description: "We need ambitious thugs with no fear of danger. This work will only be released after the interested party is contacted by us. A LOT OF MONEY will be divided. If you show talent we can definitely hire you for future thefts. come and join our team, unique opportunity.", date: Time.new(2020, 12, 18, 23, 30, 0, "+01:00") , location: "Unknow", reward: rand(500..30000))
c3 = Crime.create!(title: "Need heist specialist urgent", description: "What do we need? A complete psychopath, with no intention of the laws, easily handling weapons and bombs. Specializing in electronic theft and hacking is a differentiator for hiring. Lawyer scholarship included. We do not pay bail. Payment guaranteed in bank account created by the company. We do not hire ex-cops or individuals on the federal police's most wanted list.", date: Time.new(2020, 12, 29, 21, 00, 0, "+01:00") , location: "London", reward: rand(500..30000))
c4 = Crime.create!(title: "kidnappeding the Prime Minister Daughter, experience man/woman needed!", description: "We need an experienced woman who accepts to work as a nanny in the family of the Prime Minister of Portugal. It needs to be captivating and lethal. Absolute need for the kidnapping of the Prime Minister's daughter. Send curriculum with photo. Included guarantees to leave the country safely. Apply now and we'll send you more details.", date: Time.new(2021, 1, 2, 5, 30, 0, "+01:00") , location: "Lisbon", reward: rand(500..30000))
c5 = Crime.create!(title: "Money Heist at Bank of Spain", description: "My name is Professor I am looking for a robber who is willing to rob the bank of Spain. perfect and flawless plan. It is necessary to bring your own Salvador Dali mask for cover. Red coveralls are required. Minimum required: speak basic Spanish.", date: Time.new(2021, 1, 20, 20, 25, 0, "+01:00") , location: "Madrid", reward: rand(500..30000))

puts "skillsets created"